// Generated by CoffeeScript 1.3.3
(function() {

  YUI().use("node", function(Y) {
    return Y.namespace('Pinboard').BoardView = Y.Base.Create('boardView', Y.View, [], {
      initializer: function() {},
      render: function() {
        var test;
        return test = 1;
      }
    }, '0.0.1', {
      requires: ['view']
    });
  });

}).call(this);
